//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.DB_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemsWithDocument
    {
        public int I_D_Id { get; set; }
        public int Item_Id { get; set; }
        public int Document_Id { get; set; }
    
        public virtual Document Document { get; set; }
        public virtual Item Item { get; set; }
    }
}
