//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Utils.DB_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public Item()
        {
            this.ItemsWithDocuments = new HashSet<ItemsWithDocument>();
        }
    
        public int Item_Id { get; set; }
        public string Item_Name { get; set; }
    
        public virtual ICollection<ItemsWithDocument> ItemsWithDocuments { get; set; }
    }
}
